### ISSUE TITLE
KataGo + Tromp-Taylor

### ISSUE THREAD

**Issue by michito744** [hope366/Lizzie-improvements#20]
よろしくお願いします。

This has been going on since the original Lizzie,  when you set the search engine to KataGo and apply the Tromp-Taylor rule, it does not accept "legal suicide moves".

When you use Lizzie to analyze a phase in which you can start a legal suicide move, it shows up in the candidate move and assumption diagrams, but it does not accept input when you click on the coordinates. Also, if you load a sgf with legal suicide move, the move is skipped and the move order is wrong.

Is there any chance that this will be fixed?

**Comment by hope366** [comment]
こんにちは。
この問題については、以前公式のLizzieのIssuesでも投稿されていますね。
https://github.com/featurecat/lizzie/issues/750
PRが発表されればすぐにlizzie改良版に取り入れるつもりですが、今のところ発表されていませんね。

私はこのようなリポジトリを立ち上げてはいますが、単にlizzieのコンパイルの方法を知っているというだけで、コンピュータプログラミングに関してはほとんど知識が無いので、申し訳ありませんが貴方の質問に答えることはできません。

You've posted about this issue before in the official Lizzie's Issues.
https://github.com/featurecat/lizzie/issues/750
I will incorporate it into the lizzie improvements as soon as the PR is announced, but so far it hasn't been announced.

I'm sorry, but I can't answer your question, because I only know how to compile lizzie and have very little knowledge about computer programming, although I have set up such a repository.😅

**Comment by michito744** [comment]
了解です、ありがとうございました。
